### ISSUE TITLE
When the function finished, it still need the password?

### ISSUE THREAD

**Issue by ConanCui** [huggingface/knockknock#6] opened 2019-04-02 14:55 UTC
As the figure below, it needs the password when we start the work, it is ok cause we are on the computer now. But when the work finished, it still needs the password, we want to use this lib for convenient if we can't keep eyes on the computer, but as far, it can't solve the problem?
![image](https://user-images.githubusercontent.com/21979236/55412388-e90fe100-5599-11e9-8aa1-2d9bfdb39d6c.png)

**Comment by VictorSanh** [comment] 2019-04-02 15:13
That's odd.
I cannot reproduce your issue neither in a Jupyter or in a terminal.
Can I ask which OS you are using?

**Comment by VictorSanh** [comment] 2019-04-02 15:19
(and any other setup information that might be helpful)
It's related to the `keyring` library that is simply requesting the system keyring service for accessing or storing password. For instance, on my Mac, the Keychain app is controlling everything on top of Jupyter (so I don't have the outputs you are showing in cell [16]).

**Comment by ConanCui** [comment] 2019-04-03 02:01
Here is my setup, I try it again, and it still needs the password twice.
![image](https://user-images.githubusercontent.com/21979236/55447720-733a6280-55f7-11e9-9427-405a5865ce6c.png)

**Comment by ConanCui** [comment] 2019-04-03 02:03
Is there any setup should be done for lib 'keyring'? I just pip install it, and make no modification about it.

**Comment by VictorSanh** [comment] 2019-04-03 18:11
Since you are on Ubuntu, did you have any problems with keyring's backend?
See https://pypi.org/project/keyring/#using-keyring-on-ubuntu-16-04
Yagmail recommends using `keyrings.alt` backend.

**Comment by VictorSanh** [comment] 2019-04-25 15:20
Closing this issue since there doesn't seem to be any activity.
Feel free to re-open!
Victor

**Closed as completed by VictorSanh** 2019-04-25 15:20 UTC

**Comment by g-karthik** [comment] 2019-10-22 22:48
@VictorSanh I'm facing the exact same issue now on my AWS EC2 instance.

I was initially getting prompted the following when my train job completed:
`please enter password for encrypted keyring:`

This is pretty inconvenient and defeats the purpose of the notifications since I'll only get the start and end notifications if I am logged into the instance and I see this prompt and enter the keyring password.

So I disabled keyring by running `keyring --disable` and hoped that I won't get prompted the above message again. Now I instead get the following:

```
(pytorch_p36) [ec2-user@<my ip and dir path>]$ python testing_kk.py 
Password for <myemail@gmail.com>: 
Save username and password in keyring? [y/n]: y
Password for <myemail@gmail.com>: 
Save username and password in keyring? [y/n]: y
```

After doing the above, I get the email notifications for both train start and finish. I'm guessing the password is prompted twice because it needs to send two emails.

Can you please re-open this issue and help? Thanks!

**Comment by cpoptic** [comment] 2020-09-19 17:12
Please re-open this issue.  It still persists.
